# Generated by Django 5.1.6 on 2025-03-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
